version: "3"

services:
  dev:
    build: "."
    command: [ "sleep", "infinity" ]
    volumes:
      - ".:/app"
  
  app:
    build: "."
    command: [ "npm", "run", "run" ]
    environment:
      - "NODE_ENV=test"
    volumes:
      - ".:/app:ro"
